label: Multi Select (Select2)
status: ready
preview: '@dkfds-framed'

context:
  select_multiple_example:
    name: options
    id: js-select2-example1
    label: Vælg flere muligheder
    options: ""

      